spring.application.name=chatbot

spring.datasource.url=jdbc:postgresql://localhost:5432/chatbot-db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.1:8b

spring.jpa.show-sql=true
