spring.application.name=chatbot

spring.datasource.url=jdbc:postgresql://localhost:5432/chatbot_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

spring.ai.vectorstore.pgvector.initialize-schema=true

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.1:8b

spring.jpa.show-sql=true

weather.api.key=${WEATHER_API_KEY}
weather.base.url=https://api.openweathermap.org
weather.geo.url.path=/geo/1.0/direct
weather.current.url.path=/data/2.5/weather

spring.ai.chat.memory.repository.jdbc.initialize-schema=always